version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vg
      POSTGRES_PASSWORD: vgpass
      POSTGRES_DB: vgdb
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file: .env
    depends_on: [db, redis]
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    env_file: .env
    depends_on: [api, redis, db]
    command: celery -A app.workers.celery_app worker -l info

  beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    env_file: .env
    depends_on: [worker]
    command: celery -A app.workers.celery_app beat -l info

volumes:
  pgdata: