primary_region = "cdg"

[build]
dockerfile = "docker/Dockerfile.api"

[env]
PORT = "8000"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[checks]
  [checks.health]
  type = "http"
  port = 8000
  interval = "15s"
  timeout = "3s"
  method = "get"
  path = "/api/v1/health"

[deploy]
release_command = "alembic upgrade head"