name: Deploy to Fly
on:
  push:
    branches: ["main"]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy API
        run: flyctl deploy -c fly.api.toml --remote-only -a ${{ vars.FLY_API_APP }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-worker:
    runs-on: ubuntu-latest
    needs: deploy-api
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Worker
        run: flyctl deploy -c fly.worker.toml --remote-only -a ${{ vars.FLY_WORKER_APP }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
